### ISSUE TITLE
LoginForm.validate(): Why bother guarding against timing attacks when error messsages differ?

### ISSUE THREAD

**Issue by torotil** [Flask-Middleware/flask-security#311]
Im referring to this code snippet in `flask_security/forms.py`:

https://github.com/jwag956/flask-security/blob/b5a84402e3b63db3ca91b6b9a749561a56842119/flask_security/forms.py#L325-L336

Here both for non-exsting users and for unset passwords `hash_passwords()` is invoked. According to the comments this is to guard against timing attacks against the login form. This guard seems worthless because the error messages for each case is different. It is a lot easer to check the error messages than the timing. ;-)

**Comment by jwag956** [comment]
It's worse than you think :-)

The line:
```
        if not self.user.password:
            self.password.errors.append(get_message("PASSWORD_NOT_SET")[0])
            # Reduce timing variation between existing and non-existing users
            hash_password(self.password.data)
            return False
```

Actually doesn't run since the 'password' field has a 'required' validator.

However - I think the original intent was to keep nice UX by returning different error messages - but of course, an application could override those messages to be the same.

While it is still very common to not say whether it was the username or password that was wrong (to avoid directory attacks to find out usernames) - it is also true that due to SSO, many sites now separate out the entering of username/email and password (that's so that based on username/email they can route to the correct IDP).

Here is a recent perspective on this:
https://it.slashdot.org/story/17/12/22/1618241/username-or-password-is-incorrect-security-defense-is-a-weak-practice

I have been looking more at:
https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md
section 2.2.1. I already added breached password support.

Some slowing down I think makes sense and doesn't hurt UX - and we should probably make that uniform during login (the hash_password adds little less than a second for bcrypt).

Anti-brute force is being tracked in #207 - that also has many subtleties.
