### ISSUE TITLE
Change/Reset Email feature with confirmation email

### ISSUE THREAD

**Issue by angelxz** [Flask-Middleware/flask-security#317]
I think FS should support changing/resetting of email with confirmation. It is pretty easy to implement and I believe it would be useful for a lot of different projects. What do you guys think?

**Comment by jwag956** [comment]
Historically, FS hasn't added/supported administrative endpoints - rather providing methods (via the UserMixin) that allow applications to perform their own administration - often utilizing packages such as Flask-Admin

Email is slightly different since a) is it set up via registration/FS and b) is a field that likely would benefit from confirmation.

DId you have ideas as to what kind of confirmation - to old email and new email?

Let me think about this more - or whether it would be more  general to think up some new generic 'confirmation' endpoint...

**Comment by angelxz** [comment]
I think I didn't make myself very clear, but what I have in mind is an additional view which let's users change their email address. So they go there, type in their email (they have to be logged in), when they submit an email is being sent to them (to the new email address) with a confrimation. If the confirmation is successfull their email is changed. In a way like the reset password but with and email. (the amount of times I just wrote email is hilarious xD)

**Comment by jwag956** [comment]
You were very clear! I am making this slightly more complex :-)

Ok - I think this can make sense - and is fairly easy:
a) we should use the new @auth_required(within-xxx) feature so that changing the email requires a fresh login
b) we should send an email to both the old and new email.

**Comment by jwag956** [comment]
closed by #956
