### ISSUE TITLE
Couchdb support

### ISSUE THREAD

**Issue by Joeclinton1** [Flask-Middleware/flask-security#351]
Hi, my team is thinking of using flask-security for account management,and we are wondering if it would be possible to add support for CouchDb? 

How hard would this be to implement? Would it be possible to just convert the existing MongodbDatastore class? Is there a reason it hasn't already been done?

Thankyou.

**Comment by jwag956** [comment]
It is possible - I looked around a bit and it seems like many of the python couchdb packages are archived or not maintained. - which were you thinking of using?

For example - https://github.com/djc/couchdb-python is marked as archived - and alas is the package used by: https://pythonhosted.org/Flask-CouchDB/ - so I wouldn't use either of those.

The same appears true for: https://github.com/sirn/flask-couchdbkit.

**This looks promising: https://pypi.org/project/CouchDB2/ - though not 'flask-ized'.**

I agree that it would seem like since couchdb is a document store, starting from the mongo implementation would be a good start.

You are welcome to submit a PR - it does need to be integrated into unit tests - I am not sure if couchdb has something like 'mongomock' or precisely how that would work....

**Comment by jwag956** [comment]
Seems like interest has waned... PRs always welcome.
