### ISSUE TITLE
CSRF with AWS Fargate & Cloudfront

### ISSUE THREAD

**Issue by liquidcarbon** [Flask-Middleware/flask-security#380]
Hello, I made a docker container with a pretty simple web app: https://github.com/liquidcarbon/dockerflask2fa
The whole thing behaves well locally and when you're accessing via the ELB endpoint:
http://dockerflask2faloadbalancer-f10e5f558aaa921f.elb.us-east-1.amazonaws.com:5000

But when I use my Cloudfront distribution that lives on my domain, logging in does not work, returning "CSRF tokens do not match" message on registering a new user, and or logging in as an existing user.
https://flask.albond.xyz

The links are active.  You can register on the ELB and try to login on my site to reproduce.

I'm new to web security, and I'll appreciate your help.

**Comment by jwag956** [comment]
Couple of things - first and foremost - remember that when using forms (rather than JSON) you will almost ALWAYS get a 200 response - with errors attached to the various form elements. So just because you get 200 response from /login doesn't mean you logged in.

The matching happens by comparing the CSRF token return in the POST of the form, with the token stored in the session cookie.

SO some things to consider - is it possible that the form GET is getting cached - thus having an old CSRF token?

**Comment by liquidcarbon** [comment]
Thanks for your response!  You're right, the 200 is not relevant.
How do I check for whether the form is getting cached?

**Comment by jwag956** [comment]
You don't say if you are using JSON API or forms - and whether you have custom login forms or not.

I might start using the developer tools in say chrome - and look at the network traffic and the request/response headers -

Also - make sure that when you are making changes to your application/distribution that you clear your session cookie in your browser (using an anonymous window makes that easy).

**Comment by liquidcarbon** [comment]
It's forms, flask_wtf (see the repo in OP).  
The result is the same in an incognito window.

**Comment by jwag956** [comment]
In the response headers I see:
x-cache: Hit from cloudfront

This I think is the issue - you need to make sure the GET response of forms aren't cached since they contain the CSRF-token.

I haven't used cloudfront - but this: https://aws.amazon.com/premiumsupport/knowledge-center/prevent-cloudfront-from-caching-files/ article might be useful for testing.

This is interesting since I would presume all form-based GET requests need to not cache - but I haven't seen anything in Flask-WTF or elsewhere mention of it. Looking into that.

**Comment by jwag956** [comment]
Another thing to consider is:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Cookies.html

though I am not certain that is the issue since if you weren't passing cookies - you would get a different error message...

**Comment by liquidcarbon** [comment]
Tried some things - the problem is not yet fixed
- I changed Cloudfront Cache Policy to "Caching disabled", now token value changes every time on refreshing view-source page, but CSRF error still there
- on the ELB endpoint, there is a cookie, but not on the HTTPS endpoint

**Comment by jwag956** [comment]
Sorry you're having such issues.... If you come up with any theories etc - feel free to add to this discussion and I will try to offer any suggestions I can.

Obviously - no cookie - no workie!

**Comment by liquidcarbon** [comment]
I think I got it:
![image](https://user-images.githubusercontent.com/47034358/91676212-4f38c480-eafc-11ea-9ec9-103321573163.png)

now on the ELB endpoint, there is a cookie:
![image](https://user-images.githubusercontent.com/47034358/91675940-59a68e80-eafb-11ea-983e-f7b7bde02b71.png)


,and on the HTTPS endpoint as well:
![image](https://user-images.githubusercontent.com/47034358/91676005-9a9ea300-eafb-11ea-8954-872777913946.png)

**Comment by liquidcarbon** [comment]
Thanks a lot @jwag956 for the right pointers!

**Comment by jwag956** [comment]
So is it working? and from the above - what was the actual config required to get it going?

**Comment by liquidcarbon** [comment]
Yes, just as shown on the AWS screenshot.  Setting Origin Request Policy from blank to Managed-AllViewer made it work.  I double-checked and broke it by setting it back to blank.
