### ISSUE TITLE
version 4.0.0 doesn't accept tokens created with version 3.4.5

### ISSUE THREAD

**Issue by kuba-lilz** [Flask-Middleware/flask-security#461]
I tried migrating flask security too from 3.4.5 to 4.0.0, and noticed that api tokens created with 3.4.5 are not recognized by 4.0.0.
Is this intended? I didn't notice any mention of this in changelog.

That's a large breaking change that would affect our clients, so hopefully that's a bug that can be fixed?
I would be willing to help out if someone could point me in the right direction.

On a side note - tokens created by 4.0.0 look quite different from tokens created by 3.4.5.
With my app for the same salt and other settings they are about ~80 characters vs ~240 characters with previous tokens. Not saying that is wrong, just pointing out that probably something about token algorithm changed.

**Comment by jwag956** [comment]
It is/was intentional ... sort of. In 3.4.5 - did you have fs_uniquifier? 
In 4.0 we require it and that is the basis of the auth_token - we no longer encode the user PK and password in the token (which is why it is shorter).

It is possible we can figure out some backwards compat code

Look at verify_auth_token and https://github.com/Flask-Middleware/flask-security/pull/339

**Comment by kuba-lilz** [comment]
Thank you for the response :)

Yes, we've been using fs_uniquifier since the first version it was introduced.
Here's relevant excerpt from our users table schema:
```sql
CREATE TABLE `users` (
  `id` varchar(40) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `confirmed_at_utc` datetime DEFAULT NULL,
  `tf_primary_method` varchar(140) DEFAULT NULL,
  `tf_totp_secret` varchar(255) DEFAULT NULL,
  `fs_uniquifier` varchar(64) NOT NULL,
  `company_id` varchar(40) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_constraint_on_table_users_column_email` (`email`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

My understanding was that as long as fs_uniquifier is defined on users table, then flask security uses it to create tokens instead of the original password-based tokens (which we never used anyway).

**Comment by jwag956** [comment]
Ahh- then the fix is I think pretty easy - basically - prior to 4.0 - the auth_token had 3 parts:
id
hash(password)
fs_uniquifier

and verify_auth_token knew how to parse that.
In 4.0 - it just has:
fs_uniquifier -

So I think a 'fix' is fairly simple - in verify_auth_token - look at # of elements in the array (as the old code did)....

**Comment by kuba-lilz** [comment]
O, that's a good pointer, I'll try to look into that part of the code and come up with pull request, thank you.
