### ISSUE TITLE
Issues with sqlalchemy fs_uniquifier compatability

### ISSUE THREAD

**Issue by eneadodi** [Flask-Middleware/flask-security#706]
Earlier this year I build an application and fs_uniquifier worked perfectly well. Revisiting the library now has an issue:

`
    @app.login_manager.user_loader
    def security_login_processor(user_id):
        print(user_id)
        user = EG_User.query.get({"fs_uniquifier": user_id})
        if user:

            return user 
        else:
            print('no user found')
            return None

`

the user_loader requests a column with name 'id' however fs_uniquifier doesn't fit the naming convention.
The error code generated is:

sqlalchemy.exc.InvalidRequestError: Incorrect names of values in identifier to formulate primary key for session.get(); primary key attribute names are 'id' (synonym names are also accepted)

Is there a work around for this issue? It dosen't seem to be a common issue on google.

**Comment by eneadodi** [comment]
quick workaround is to simply return self.id for get_id. However isn't this the point of the 'fs_uniqufier' to be used?

**Comment by jwag956** [comment]
redefining the user_loader is probably a really bad idea! since flask_security sort of depends on that!

Look at UserMixin which defines get_id() to return fs_uniquifier - and that is what flask_login ultimately uses.


Look also at flask_login -alternative token - we explicitly do NOT want the primary key to be the security token - since that means you can't really reset a user's security credentials without changing the primary key - and that basically means you have to create a new user. That's why we invented fs_uniquifier - it also decouples flask-security from primary key - so you can make the primary key whatever you want.
