### ISSUE TITLE
authentication token not returned when logging in with 2fa enabled

### ISSUE THREAD

**Issue by lilz-egoto** [Flask-Middleware/flask-security#861]
This is for the external api with json. The documentation says that the authentication token will be returned if include_auth_token is in the query params, but with 2fa enabled, the auth token is not returned.
<img width="1077" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/d1401110-977b-4783-8285-1c83b0db6d4d">
<img width="629" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/8687d618-ab29-4f74-839f-d2802d2b4b28">

A csrf token is returned but that is not part of the schema

**Comment by lilz-egoto** [comment]
It seems like if the user has 2fa enabled, the auth token isn't returned. The auth token for a user without 2fa enabled is also returned under a user object as well so the schema is not very accurate. 
<img width="647" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/70d0071b-44bb-4077-9979-b8d97d5480fa">

**Comment by jwag956** [comment]
In your case - the reason you aren't getting the authentication_token is because you haven't completely authenticated yet - your test passed the primary authentication but as the return JSON states - 'tf_required' is true - so you have to complete the second factor prior to being fully authenticated and then able to retrieve the authentication_token.
But there was in fact a bug - /tf-validate which is used for the second factor wasn't honoring ?include_auth_token. That has been fixed along with lots of documentation improvements.

**Comment by lilz-egoto** [comment]
Thanks, I see that user is part of the schema now
