### ISSUE TITLE
ValueError: The name 'security' is already registered for a different blueprint. Use 'name=' to provide a unique name.

### ISSUE THREAD

**Issue by princerb** [Flask-Middleware/flask-security#883]
❓ This is just a quick question. Is there a way that we can use multiple Security() instances?

For example, I wanted to use the security in a single flask app, but with different points: for users and admins.

📟 Code would look like this:

**admin_sec.py**
```py
# ... AdminUsersRoles, AdminUser, AdminUserRole models here
admin_datastore = SQLAlchemyUserDatastore(db, AdminUser, AdminUserRole)
security = Security(datastore=admin_datastore)
```
**user_sec.py**
```py
# ... UsersRoles, User, Role models here
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(datastore=user_datastore)
```
**app.py**
```py
from .user_sec import security as user_security
user_security.init_app(app)
from .admin_sec import security as admin_security
admin_security.init_app(app)
```
Then admin security route should be like `/admin/dashboard/login`,
user securtiy route should be like `/dashboard/login`.

But it is causing the error titled. I tried to set params like `name`, `url`, `prefix` to the core, but it didn't help.

**Please tell me there is a way or not. Or please leave some code with no multiple instances to achieve what I am gonna do here. Thanks.**

**Comment by jwag956** [comment]
Consider using: https://flask-security-too.readthedocs.io/en/stable/configuration.html#SECURITY_BLUEPRINT_NAME
for your immediate issue.

Also - having 2 different instances and 2 different user models seems very complex. Why not use 'roles' and 'permissions' to protect your various endpoints and have a single user database. If you think about down the road - a single DB lets you add/modify user's permissions - just because a user isn't an admin anymore should mean they have to re-sign up for your application...

**Comment by princerb** [comment]
You're right, using 2 different user models is more complex, but due to the application structure I have to apply two of them.
I'll try [SECURITY_BLUEPRINT_NAME](https://flask-security-too.readthedocs.io/en/stable/configuration.html#SECURITY_BLUEPRINT_NAME) as you said, but I think authentication might get wrong as both security instances will use the same cookie and session (_user_id) fields.

**Comment by jwag956** [comment]
Please open new issue if things still aren't working
