### ISSUE TITLE
Login via social/oauth not respecting SECURITY_REDIRECT_HOST

### ISSUE THREAD

**Issue by mmillmore** [Flask-Middleware/flask-security#884]
If I enable google login, and I have SECURITY_REDIRECT_HOST set, when I click on the google login button, the redirect URL is to the original host, not the redirect host, e.g. if I am running on localhost:5000 with SECURITY_REDIRECT_HOST =localhost:4000, I get a Google URL which has 

https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=XXX&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fadmin%2Flogin%2Foauthresponse%2Fgoogle&scope=openid+email+profile&state=XXX&nonce=XXX

**Comment by mmillmore** [comment]
Adding to this, the code in validate_redirect_url in ./utils.py checks that the URL matches request.host_url, but when SECURITY_REDIRECT_HOST, the request.host_url doesn't match that - it matches the SECURITY_REDIRECT_HOST

**Comment by jwag956** [comment]
I was reviewing your code - and coming back to this issue - I think there is a misunderstanding of what SECURITY_REDIRECT_HOST is for - it is specifically for use with SPA front-ends to allow them to intercept redirects that Flask-Security performs (usually at the end of a view - such as /login/oauthresponse). In this case - the oauth provider is redirecting back to Flask-Security's view - as it should. I don't understand why your application would want it to go anywhere else.

Help me understand your use case better... thanks

**Comment by mmillmore** [comment]
My front end is 100% in react. I have SECURITY_REDIRECT_BEHAVIOR=spa and SECURITY_REDIRECT_HOST=localhost:4000. I have a login screen in react, and on it is a button to Login With Google. That button does a POST to /login/oauthstart/google as described at https://flask-security-too.readthedocs.io/en/stable/_static/openapi_view.html#post-/login/oauthstart/-name-

I expect it to take me to the Google login screen., allow me to log in, and return to the post login page. That gets into all sorts of problems because the redirect URL is sometimes valid and sometimes not - sometimes it points to the SECURITY_REDIRECT_HOST (e.g. if the user is already logged in I think it never goes to Google, but goes to a post login error page, which is on SECURITY_REDIRECT_HOST ) , and validate_redirect_url errors under those circumstances because it only respects redirects to the orginal host, not SECURITY_REDIRECT_HOST. For that reason, we need to have validate_redirect_url updated to respect the SECURITY_REDIRECT_HOST.

We also need to never go to the original host at all. When deployed in a cloud environment, the original host will be going through a load balancer, and presenting to the outside world as a different URL. The host URL might be localhost:8000 while the outside world sees it as myapp.com. Any calls from the oauth provider back to localhost:8000/login/oauthresponse aren't going to work. We need that to go to myapp.com/login/oauthresponse, so we need get_redirect to change to set the redirect URL based on SECURITY_REDIRECT_HOST.

**Comment by mmillmore** [comment]
I made a sample app at https://github.com/mmillmore/flask-security-test-cases so that you can see what I am doing. If you log in you will see it erroring complaining about no valid redirect. If this is simply an issue with my app, I'd be delighted to be corrected!

**Comment by jwag956** [comment]
Thanks - I have that downloaded and working. This is precisely the use case REDIRECT_HOST was designed for and in my testing - is working perfectly.

A couple things:

- POST_LOGIN_VIEW - this was re-used in oauth and really shouldn't be - since it means you cant BOTH do SPA and forms - so I will fix this and create a new xx_VIEW that can be set just for SPA. I think this might be what is causing your 'sometimes valid and sometimes not' issue.
-  /login and /us-signin both have special code if called when already authenticated - which oauthstart doesn't - it probably should just return a JSON response - I will look into fixing that.
- POST_LOGOUT_VIEW - isn't for SPA - you should be sending in a JSON request and not doing any redirection. However for testing you can set it to an ENDPOINT - such as ".login". This was one cause of 'no valid redirect'.
- Your react frontend isn't set up to actually call the backend for '/' or '/user' - you probably want to set your backend as a blueprint with a prefix like '/backend'.

**Comment by mmillmore** [comment]
Thanks for looking at this. I realise in my attempt to produce a stripped down test case, I stripped too much out. I have updated my test case now - I added in a check for whether you are logged, and set the correct path for the service.

If you need any help with implementation, let me know - glad to help if I can

**Comment by jwag956** [comment]
Just tried that - still seems to work - I see the UI calling /admin/current_user and getting a 401 prior to logging in - then 200 after that. If I go to localhost:5010:/admin/current_user - I get reasonable output. Can you provide actual steps you are performing and the un-expected output?
