### ISSUE TITLE
/login JSON api accepts CSRF token through the body

### ISSUE THREAD

**Issue by lilz-egoto** [Flask-Middleware/flask-security#943]
When using the JSON api and sending POST /login with a JSON body, adding `csrf_token` as a third key in the body lets you successfully login. Is this as intended? 

<img width="1237" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/5abc315a-710a-4705-9c5c-083b8b6b7177">

Headers for the same request:
<img width="609" alt="image" src="https://github.com/Flask-Middleware/flask-security/assets/114893596/9679b140-9f21-4c05-a534-e00ea2ce7679">

The security related settings I have are:
```
app.config["SECURITY_CSRF_COOKIE_NAME"] = "CSRF-Cookie"
app.config["SECURITY_CSRF_HEADER"] = "CSRF-Header"
app.config["SECURITY_CSRF_PROTECT_MECHANISMS"] = ["session"]
app.config["WTF_CSRF_TIME_LIMIT"] = 900
app.config["WTF_CSRF_CHECK_DEFAULT"] = False
app.config["SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS"] = False

flask_wtf.CSRFProtect(app)
```

In the CSRF Pro tips section of the [documentation](https://flask-security-too.readthedocs.io/en/stable/patterns/#csrf-pro-tips) it is stated that,
`If you enable CSRFProtect(app) and you want to send request data as JSON, then you must include the CSRF token in the header` 
but it seems we have bypassed this protection.

**Comment by lilz-egoto** [comment]
Ok well I see now that most liekly has to do with flask-wtf: https://flask-wtf.readthedocs.io/en/0.15.x/config/#configuration

**Comment by jwag956** [comment]
This is all way more complex than I wish due to all the various config parameters.
The TL;DR is that with the recent PR - this actually won't work anymore which is fine.
There wasn't any protection bypassed - before this recent change if the first CSRF check failed (the one our decorator does) fails - it would pass through to the form where another CSRF check was done.
Whew!

It is worth pointing out that regardless of whether the client sends JSON or forms - both are converted (by Flask) into a form - which is then validated (where csrf is checked).

**Comment by lilz-egoto** [comment]
Thank you, I have verified the updated functionality on 5.4.3
